### ISSUE TITLE
Bug: pronto/flay does not respect values in `.flayignore`

### ISSUE THREAD

**Issue by mknapik** [mmozuras/pronto-flay#10] opened 2016-04-20 15:41 UTC
To reproduce the issue follow the steps in the repository: [mknapik/pronto-flay-ignore-issue](https://github.com/mknapik/pronto-flay-ignore-issue).

`.flayignore` contents:

```
spec/**/*.rb
```

```bash
$ flay .
```

returns

```
Total score (lower is better) = 64

1) Similar code found in :defs (mass = 64)
  lib/duplication.rb:2
  lib/duplication.rb:8
```

```bash
$ pronto run -r flay -c 596484d
```

returns

```
lib/duplication.rb:2 W: Similar code found in duplication.rb:2, duplication.rb:8
lib/duplication.rb:8 W: Similar code found in duplication.rb:2, duplication.rb:8
spec/duplication_spec.rb:14 W: Similar code found in duplication_spec.rb:14, duplication_spec.rb:21, duplication_spec.rb:28, duplication_spec.rb:35, duplication_spec.rb:42, duplication_spec.rb:49
spec/duplication_spec.rb:21 W: Similar code found in duplication_spec.rb:14, duplication_spec.rb:21, duplication_spec.rb:28, duplication_spec.rb:35, duplication_spec.rb:42, duplication_spec.rb:49
spec/duplication_spec.rb:28 W: Similar code found in duplication_spec.rb:14, duplication_spec.rb:21, duplication_spec.rb:28, duplication_spec.rb:35, duplication_spec.rb:42, duplication_spec.rb:49
spec/duplication_spec.rb:35 W: Similar code found in duplication_spec.rb:14, duplication_spec.rb:21, duplication_spec.rb:28, duplication_spec.rb:35, duplication_spec.rb:42, duplication_spec.rb:49
spec/duplication_spec.rb:42 W: Similar code found in duplication_spec.rb:14, duplication_spec.rb:21, duplication_spec.rb:28, duplication_spec.rb:35, duplication_spec.rb:42, duplication_spec.rb:49
spec/duplication_spec.rb:49 W: Similar code found in duplication_spec.rb:14, duplication_spec.rb:21, duplication_spec.rb:28, duplication_spec.rb:35, duplication_spec.rb:42, duplication_spec.rb:49
```

I believe the issue lies in the fact that `flay` uses relative paths (`String` array though I've checked relative `Pathname`s and it works as well) and `pronto/flay` passes absolute paths (`Pathname` objects).

So actually running flay with absolute paths does not respect `.flayignore` as well.

```bash
flay `pwd`/
```

```
Total score (lower is better) = 178

1) Similar code found in :iter (mass = 114)
  /tmp/pronto-flay-ignore-issue/spec/duplication_spec.rb:14
  /tmp/pronto-flay-ignore-issue/spec/duplication_spec.rb:21
  /tmp/pronto-flay-ignore-issue/spec/duplication_spec.rb:28
  /tmp/pronto-flay-ignore-issue/spec/duplication_spec.rb:35
  /tmp/pronto-flay-ignore-issue/spec/duplication_spec.rb:42
  /tmp/pronto-flay-ignore-issue/spec/duplication_spec.rb:49

2) Similar code found in :defs (mass = 64)
  /tmp/pronto-flay-ignore-issue/lib/duplication.rb:2
  /tmp/pronto-flay-ignore-issue/lib/duplication.rb:8
```

So actually I'm not sure whether we should fix `pronto-flay` and pass relative paths or fix `flay` itself to recognise absolute paths.
@mmozuras @seattlerb What do you think?

**Comment by mknapik** [comment] 2016-05-09 21:36
@mmozuras Bump. Any thoughts regarding the issue?

**Comment by mknapik** [comment] 2016-05-12 13:30
I've prepared a patch for flay: https://github.com/seattlerb/flay/pull/58

**Comment by mmozuras** [comment] 2016-05-15 18:56
@mknapik sorry for taking a while to answer, had a busy month 😄 

The PR you've done for `flay` makes total sense for me. Let's see where that goes before doing anything in `pronto-flay` 👍 🙇

**Comment by mknapik** [comment] 2016-05-15 22:03
No problem, it's good to know the issue is on your radar!

**Comment by abinoam** [comment] 2016-05-31 06:28
(I was just about to open a new issue when I saw that it is close related to this on. A "consequence" of it, in fact).

I'm having ```undefined method `filter_files' for Flay:Class (NoMethodError)``` with pronto-flay:
```
/Users/abinoam/.rvm/gems/ruby-2.3.1/gems/pronto-flay-0.6.1/lib/pronto/flay.rb:8:in `run': undefined method `filter_files' for Flay:Class (NoMethodError)
	from /Users/abinoam/.rvm/gems/ruby-2.3.1/gems/pronto-0.6.0/lib/pronto/runners.rb:16:in `block in run'
	from /Users/abinoam/.rvm/gems/ruby-2.3.1/gems/pronto-0.6.0/lib/pronto/runners.rb:13:in `each'
	from /Users/abinoam/.rvm/gems/ruby-2.3.1/gems/pronto-0.6.0/lib/pronto/runners.rb:13:in `run'
	from /Users/abinoam/.rvm/gems/ruby-2.3.1/gems/pronto-0.6.0/lib/pronto.rb:42:in `run'
	from /Users/abinoam/.rvm/gems/ruby-2.3.1/gems/pronto-0.6.0/lib/pronto/cli.rb:52:in `run'
	from /Users/abinoam/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/abinoam/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/abinoam/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/abinoam/.rvm/gems/ruby-2.3.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/abinoam/.rvm/gems/ruby-2.3.1/gems/pronto-0.6.0/bin/pronto:6:in `<top (required)>'
	from /Users/abinoam/.rvm/gems/ruby-2.3.1/bin/pronto:23:in `load'
	from /Users/abinoam/.rvm/gems/ruby-2.3.1/bin/pronto:23:in `<main>'
	from /Users/abinoam/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/abinoam/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

It's probably related to this commit in flay https://github.com/seattlerb/flay/commit/4781d22de036dcb6976ff5c04d38569b9912faae where @zenspider has dropped Flay.filter_files in favor of a better approach. (Of importance this comment https://github.com/seattlerb/flay/pull/58#issuecomment-218890546)

@mmozuras Could you fix pronto-flay to this new approach in Flay? I'm not confident enough at pronto-flay code to try fixing it my self.

**Comment by mknapik** [comment] 2016-05-31 09:40
I guess we could pin version to flay `2.7.0` or update the implementation.

**Comment by abinoam** [comment] 2016-05-31 20:17
I think I have a fix for this.
Uploading the PR in some minutes.

**Comment by abinoam** [comment] 2016-05-31 21:00
Dear @mknapik 

I have checked the PR #11 against your (very well documented) use case at https://github.com/mknapik/pronto-flay-ignore-issue.
We still have an issue.
To make it work as you're expecting you should precede the path with double stars.
So instead of...

``` spec/**/*.rb ```

... you should use ...

``` **/spec/**/*.rb ```

... and it will work as expected.

Could you double check it?

Absolute vs. relative path difference might be playing some role in this issue.

**Comment by zenspider** [comment] 2016-06-01 00:38
I'm not sure why the extra "**" is needed?

**Comment by abinoam** [comment] 2016-06-01 01:24
pronto-flay is making some "tweaking" before passing the filenames to flay. I was able to debug until find out that it passes Pathname objects, not strings. And perhaps this make the PathExpander#filter_files to fail on File.fnmatch? (But, I didn't dig deep enough to understand clearly how it all fit together. So this is a guess).

**Comment by abinoam** [comment] 2016-06-01 01:25
... so the ** just make sure that it matches the "end part" of the filename even if it doesn't match the begining of the path.

**Comment by abinoam** [comment] 2016-06-01 01:26
Flay itself seems to work well without these double stars. The issue is really related to pronto-flay.

**Closed** 2016-07-03 16:06 UTC
